apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clipper-backend
  labels:
    app: clipper-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - clpr.tv
      secretName: clipper-tls
  rules:
    - host: clpr.tv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clipper-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clipper-backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: clipper-backend
                port:
                  number: 80
