apiVersion: v1
kind: Service
metadata:
  name: clipper-backend
  labels:
    app: clipper-backend
spec:
  type: ClusterIP
  selector:
    app: clipper-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
