apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clipper-backend
  namespace: clipper-production
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.clpr.tv
      secretName: clipper-backend-tls-prod
  rules:
    - host: api.clpr.tv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clipper-backend
                port:
                  number: 80
