apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clipper-postgres.fullname" . }}-config
  labels:
    {{- include "clipper-postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.database | quote }}
  POSTGRES_USER: {{ .Values.config.username | quote }}
