---
apiVersion: v1
kind: Namespace
metadata:
  name: clipper-production
  labels:
    name: clipper-production
    environment: production
    managed-by: clipper-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: clipper-staging
  labels:
    name: clipper-staging
    environment: staging
    managed-by: clipper-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: clipper-monitoring
  labels:
    name: clipper-monitoring
    environment: shared
    managed-by: clipper-ops
