apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clipper-backend.fullname" . }}-config
  labels:
    {{- include "clipper-backend.labels" . | nindent 4 }}
    component: config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
